<?php

namespace Database\Seeders;

use App\Models\Album;
use App\Models\Artist;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;

class AudioCatalogSeeder extends Seeder
{
    public function run(): void
    {
        collect($this->data())
            ->each(fn (array $albumData) => $this->seedAlbum($albumData));
    }

    protected function data(): array
    {
        return [
            // Ado - 3 albums
            [
                'artist' => 'Ado',
                'artist_slug' => 'ado',
                'title' => 'Ado Spectrum',
                'slug' => 'ado-spectrum',
                'type' => 'album',
                'genre' => 'J-Pop',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2025-04-08',
                'originated' => '2025-04-09',
                'label' => 'Universal Music LLC',
                'duration' => '42m 18s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/ado-spectrum.svg',
                    'alt' => 'Ado Spectrum cover artwork',
                    'palette' => ['#1b1f3a', '#6a2336', '#6dd3ff'],
                    'accent' => '#f4f7fb',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/ado/ado-spectrum.zip',
                    'filename' => 'ado-spectrum.zip',
                    'label' => 'Download Album',
                    'size' => '892 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC and lossless download formats',
                    'note' => 'A dramatic vocal-forward release tuned for a bright storefront presentation.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Usseewa', 'artist' => 'Ado', 'duration' => '3:26'],
                    ['number' => '1.2', 'title' => 'Ashura-chan', 'artist' => 'Ado', 'duration' => '3:17'],
                    ['number' => '1.3', 'title' => 'Yoru no Pierrot', 'artist' => 'Ado', 'duration' => '3:20'],
                    ['number' => '1.4', 'title' => 'Odo', 'artist' => 'Ado', 'duration' => '3:32'],
                    ['number' => '1.5', 'title' => 'Sakura Biyori and Time Machine', 'artist' => 'Ado feat. Miku Hatsune', 'duration' => '5:31'],
                ],
                'editor_notes' => 'Built as the lead release for the demo catalog, this album anchors the storefront with sharper colors and a dramatic hero presentation.',
            ],
            [
                'artist' => 'Ado',
                'artist_slug' => 'ado',
                'title' => 'Neon Reverie',
                'slug' => 'neon-reverie',
                'type' => 'ep',
                'genre' => 'Alternative',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2024-10-02',
                'originated' => '2024-10-02',
                'label' => 'Virgo Sound',
                'duration' => '24m 04s',
                'featured' => true,
                'recommended' => false,
                'cover' => [
                    'image' => 'images/audio/neon-reverie.svg',
                    'alt' => 'Neon Reverie package artwork',
                    'palette' => ['#101b36', '#ff6a88', '#ff99ac'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/ado/neon-reverie.zip',
                    'filename' => 'neon-reverie.zip',
                    'label' => 'Download EP',
                    'size' => '312 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC and lossless digital formats',
                    'note' => 'A tighter five-track EP with brighter synth textures and a punchier presentation.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Mirage Window', 'artist' => 'Ado', 'duration' => '4:08'],
                    ['number' => '1.2', 'title' => 'High Tide Voice', 'artist' => 'Ado', 'duration' => '4:41'],
                    ['number' => '1.3', 'title' => 'Red Orbit', 'artist' => 'Ado', 'duration' => '5:20'],
                ],
                'editor_notes' => 'The EP format gives the landing page a smaller release shape so the grid does not look repetitive.',
            ],
            [
                'artist' => 'Ado',
                'artist_slug' => 'ado',
                'title' => 'WONDERFUL',
                'slug' => 'wonderful',
                'type' => 'single',
                'genre' => 'J-Pop',
                'formats' => ['FLAC', '24-bit'],
                'release_date' => '2025-01-15',
                'originated' => '2025-01-15',
                'label' => 'Universal Music LLC',
                'duration' => '18m 45s',
                'featured' => false,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/wonderful.svg',
                    'alt' => 'WONDERFUL single artwork',
                    'palette' => ['#ffecd2', '#fcb69f', '#ff6b6b'],
                    'accent' => '#1a1a2e',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/ado/wonderful.zip',
                    'filename' => 'wonderful.zip',
                    'label' => 'Download Single',
                    'size' => '156 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC format',
                    'note' => 'A vibrant single with high-energy production.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'WONDERFUL', 'artist' => 'Ado', 'duration' => '4:23'],
                    ['number' => '1.2', 'title' => 'Dreamland', 'artist' => 'Ado', 'duration' => '4:45'],
                ],
                'editor_notes' => 'A high-energy single that showcases Ado\'s vocal range.',
            ],

            // Sakurazaka46 - 2 albums
            [
                'artist' => 'Sakurazaka46',
                'artist_slug' => 'sakurazaka46',
                'title' => 'Blue Hour Parade',
                'slug' => 'blue-hour-parade',
                'type' => 'album',
                'genre' => 'Idol',
                'formats' => ['FLAC', '24-bit'],
                'release_date' => '2025-01-14',
                'originated' => '2025-01-15',
                'label' => 'Seed & Flower',
                'duration' => '51m 22s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/blue-hour-parade.svg',
                    'alt' => 'Blue Hour Parade portrait artwork',
                    'palette' => ['#0f2240', '#7cc2ff', '#fff0d5'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/sakurazaka46/blue-hour-parade.zip',
                    'filename' => 'blue-hour-parade.zip',
                    'label' => 'Download Album',
                    'size' => '1.1 GB',
                ],
                'specs' => [
                    'audio' => 'Available in 96 kHz / 24-bit FLAC and standard lossless audio formats',
                    'note' => 'Wide stereo pop mixes with a softer upper-mid balance and a cleaner idol-pop shelf presence.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '96 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Blue Hour Parade', 'artist' => 'Sakurazaka46', 'duration' => '4:12'],
                    ['number' => '1.2', 'title' => 'Glass Corridor', 'artist' => 'Sakurazaka46', 'duration' => '3:56'],
                    ['number' => '1.3', 'title' => 'Moonline Signal', 'artist' => 'Sakurazaka46', 'duration' => '4:02'],
                    ['number' => '1.4', 'title' => 'Silent Carousel', 'artist' => 'Sakurazaka46', 'duration' => '4:18'],
                    ['number' => '1.5', 'title' => 'White Season', 'artist' => 'Sakurazaka46', 'duration' => '4:40'],
                ],
                'editor_notes' => 'This release represents the polished idol-pop side of the storefront with a brighter, lighter cover balance.',
            ],
            [
                'artist' => 'Sakurazaka46',
                'artist_slug' => 'sakurazaka46',
                'title' => 'Afterglow Archive',
                'slug' => 'afterglow-archive',
                'type' => 'single',
                'genre' => 'J-Pop',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2024-07-19',
                'originated' => '2024-07-19',
                'label' => 'Seed & Flower',
                'duration' => '14m 07s',
                'featured' => false,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/afterglow-archive.svg',
                    'alt' => 'Afterglow Archive color-splash artwork',
                    'palette' => ['#3b0f3e', '#f093fb', '#f5576c'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/sakurazaka46/afterglow-archive.zip',
                    'filename' => 'afterglow-archive.zip',
                    'label' => 'Download Single',
                    'size' => '145 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC and standard lossless formats',
                    'note' => 'A shorter release with enough color contrast to break up the main album rows.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Afterglow Archive', 'artist' => 'Sakurazaka46', 'duration' => '4:19'],
                    ['number' => '1.2', 'title' => 'Quiet Voltage', 'artist' => 'Sakurazaka46', 'duration' => '4:44'],
                ],
                'editor_notes' => 'Single-format entries help the audio homepage feel like a real catalog instead of a flat wall of same-sized albums.',
            ],

            // Nogizaka46 - 2 albums
            [
                'artist' => 'Nogizaka46',
                'artist_slug' => 'nogizaka46',
                'title' => 'White Echo',
                'slug' => 'white-echo',
                'type' => 'album',
                'genre' => 'J-Pop',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2024-11-23',
                'originated' => '2024-11-25',
                'label' => 'Sony Music Labels',
                'duration' => '47m 33s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/white-echo.svg',
                    'alt' => 'White Echo station-themed artwork',
                    'palette' => ['#eef4ff', '#9fc4ff', '#5686d6'],
                    'accent' => '#0d1521',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/nogizaka46/white-echo.zip',
                    'filename' => 'white-echo.zip',
                    'label' => 'Download Album',
                    'size' => '856 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC and lossless digital formats',
                    'note' => 'Cleaner vocal blend, smoother high-end, and a softer visual identity for the storefront.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'White Echo', 'artist' => 'Nogizaka46', 'duration' => '4:03'],
                    ['number' => '1.2', 'title' => 'Starlight Hall', 'artist' => 'Nogizaka46', 'duration' => '4:11'],
                    ['number' => '1.3', 'title' => 'Paper Snow', 'artist' => 'Nogizaka46', 'duration' => '3:49'],
                    ['number' => '1.4', 'title' => 'Signal Bloom', 'artist' => 'Nogizaka46', 'duration' => '4:27'],
                ],
                'editor_notes' => 'This album gives the storefront a cooler palette and a gentler cover arrangement for the recommended row.',
            ],
            [
                'artist' => 'Nogizaka46',
                'artist_slug' => 'nogizaka46',
                'title' => 'Velvet Transit',
                'slug' => 'velvet-transit',
                'type' => 'single',
                'genre' => 'Ballad',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2025-02-12',
                'originated' => '2025-02-12',
                'label' => 'Sony Music Labels',
                'duration' => '16m 18s',
                'featured' => false,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/velvet-transit.svg',
                    'alt' => 'Velvet Transit group train artwork',
                    'palette' => ['#101010', '#54407a', '#d8c7ff'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/nogizaka46/velvet-transit.zip',
                    'filename' => 'velvet-transit.zip',
                    'label' => 'Download Single',
                    'size' => '178 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC and lossless digital formats',
                    'note' => 'A softer ballad-centered release that works well as a recommendation card on the detail page.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Velvet Transit', 'artist' => 'Nogizaka46', 'duration' => '5:02'],
                    ['number' => '1.2', 'title' => 'Quiet Lens', 'artist' => 'Nogizaka46', 'duration' => '5:21'],
                ],
                'editor_notes' => 'This entry is here to keep the recommendation rail from being dominated only by full albums.',
            ],

            // YOASOBI - 2 albums
            [
                'artist' => 'YOASOBI',
                'artist_slug' => 'yoasobi',
                'title' => 'Oshi no Ko',
                'slug' => 'oshi-no-ko',
                'type' => 'album',
                'genre' => 'Electronic',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2024-06-12',
                'originated' => '2024-06-12',
                'label' => 'Sony Music Japan',
                'duration' => '38m 45s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/oshi-no-ko.svg',
                    'alt' => 'Oshi no Ko anime soundtrack cover',
                    'palette' => ['#ff1744', '#ff5252', '#ff8a80'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/yoasobi/oshi-no-ko.zip',
                    'filename' => 'oshi-no-ko.zip',
                    'label' => 'Download Album',
                    'size' => '524 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC and lossless formats',
                    'note' => 'Anime soundtrack with electronic production and catchy melodies.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Idol', 'artist' => 'YOASOBI', 'duration' => '3:48'],
                    ['number' => '1.2', 'title' => 'Mixed Nuts', 'artist' => 'YOASOBI', 'duration' => '3:24'],
                    ['number' => '1.3', 'title' => 'Bling-Bang-Bang-Born', 'artist' => 'YOASOBI', 'duration' => '4:12'],
                ],
                'editor_notes' => 'One of the most popular anime soundtracks of 2024.',
            ],
            [
                'artist' => 'YOASOBI',
                'artist_slug' => 'yoasobi',
                'title' => 'Color of Sky',
                'slug' => 'color-of-sky',
                'type' => 'ep',
                'genre' => 'Electronic',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2025-03-05',
                'originated' => '2025-03-05',
                'label' => 'Sony Music Japan',
                'duration' => '22m 30s',
                'featured' => false,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/color-of-sky.svg',
                    'alt' => 'Color of Sky EP cover',
                    'palette' => ['#e3f2fd', '#90caf9', '#42a5f5'],
                    'accent' => '#0d47a1',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/yoasobi/color-of-sky.zip',
                    'filename' => 'color-of-sky.zip',
                    'label' => 'Download EP',
                    'size' => '245 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC and lossless formats',
                    'note' => 'A dreamy EP with atmospheric electronic production.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Color of Sky', 'artist' => 'YOASOBI', 'duration' => '4:15'],
                    ['number' => '1.2', 'title' => 'Trillion Star', 'artist' => 'YOASOBI', 'duration' => '4:02'],
                    ['number' => '1.3', 'title' => 'Midnight Sun', 'artist' => 'YOASOBI', 'duration' => '3:55'],
                ],
                'editor_notes' => 'A more atmospheric and dreamy release from YOASOBI.',
            ],

            // Radwimps - 2 albums
            [
                'artist' => 'Radwimps',
                'artist_slug' => 'radwimps',
                'title' => 'Weather With You',
                'slug' => 'weather-with-you',
                'type' => 'album',
                'genre' => 'Rock',
                'formats' => ['FLAC', '24-bit'],
                'release_date' => '2024-05-03',
                'originated' => '2024-05-03',
                'label' => 'Universal Music Japan',
                'duration' => '45m 22s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/weather-with-you.svg',
                    'alt' => 'Weather With You album cover',
                    'palette' => ['#ff9800', '#ffe082', '#fff8e1'],
                    'accent' => '#e65100',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/radwimps/weather-with-you.zip',
                    'filename' => 'weather-with-you.zip',
                    'label' => 'Download Album',
                    'size' => '678 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 96 kHz / 24-bit FLAC format',
                    'note' => 'Rock with orchestral elements, signature Radwimps sound.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '96 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Weather With You', 'artist' => 'Radwimps', 'duration' => '5:12'],
                    ['number' => '1.2', 'title' => 'Nandemonaiya', 'artist' => 'Radwimps', 'duration' => '5:18'],
                    ['number' => '1.3', 'title' => 'Sparkle', 'artist' => 'Radwimps', 'duration' => '4:45'],
                    ['number' => '1.4', 'title' => 'Zenzenzense', 'artist' => 'Radwimps', 'duration' => '5:25'],
                ],
                'editor_notes' => 'One of Radwimps\' most iconic albums with Your Name soundtrack hits.',
            ],
            [
                'artist' => 'Radwimps',
                'artist_slug' => 'radwimps',
                'title' => 'Humanity',
                'slug' => 'humanity',
                'type' => 'album',
                'genre' => 'Alternative',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2023-11-22',
                'originated' => '2023-11-22',
                'label' => 'Universal Music Japan',
                'duration' => '52m 10s',
                'featured' => false,
                'recommended' => false,
                'cover' => [
                    'image' => 'images/audio/humanity.svg',
                    'alt' => 'Humanity album cover',
                    'palette' => ['#263238', '#546e7a', '#90a4ae'],
                    'accent' => '#eceff1',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/radwimps/humanity.zip',
                    'filename' => 'humanity.zip',
                    'label' => 'Download Album',
                    'size' => '712 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC and lossless formats',
                    'note' => 'A more experimental rock album with diverse sound.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Tunnel', 'artist' => 'Radwimps', 'duration' => '4:33'],
                    ['number' => '1.2', 'title' => 'SOS', 'artist' => 'Radwimps', 'duration' => '4:08'],
                    ['number' => '1.3', 'title' => 'Machiavellian', 'artist' => 'Radwimps', 'duration' => '4:42'],
                ],
                'editor_notes' => 'A more experimental approach to rock music.',
            ],

            // Lisa - 2 albums
            [
                'artist' => 'LiSA',
                'artist_slug' => 'lisa',
                'title' => 'Landers',
                'slug' => 'landers',
                'type' => 'album',
                'genre' => 'Rock',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2024-09-25',
                'originated' => '2024-09-25',
                'label' => 'Sony Music Japan',
                'duration' => '48m 35s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/landers.svg',
                    'alt' => 'Landers album cover',
                    'palette' => ['#1a237e', '#3949ab', '#7986cb'],
                    'accent' => '#c5cae9',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/lisa/landers.zip',
                    'filename' => 'landers.zip',
                    'label' => 'Download Album',
                    'size' => '823 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC format',
                    'note' => 'Powerful rock with anime opening hits.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Landers', 'artist' => 'LiSA', 'duration' => '4:22'],
                    ['number' => '1.2', 'title' => 'Shironeko', 'artist' => 'LiSA', 'duration' => '4:08'],
                    ['number' => '1.3', 'title' => 'Undead', 'artist' => 'LiSA', 'duration' => '3:55'],
                    ['number' => '1.4', 'title' => 'Rash', 'artist' => 'LiSA', 'duration' => '4:15'],
                ],
                'editor_notes' => 'LiSA\'s signature rock sound with powerful vocals.',
            ],
            [
                'artist' => 'LiSA',
                'artist_slug' => 'lisa',
                'title' => 'Like or Love',
                'slug' => 'like-or-love',
                'type' => 'single',
                'genre' => 'J-Pop',
                'formats' => ['FLAC', '24-bit'],
                'release_date' => '2025-02-14',
                'originated' => '2025-02-14',
                'label' => 'Sony Music Japan',
                'duration' => '15m 20s',
                'featured' => false,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/like-or-love.svg',
                    'alt' => 'Like or Love single cover',
                    'palette' => ['#f48fb1', '#f06292', '#ec407a'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/lisa/like-or-love.zip',
                    'filename' => 'like-or-love.zip',
                    'label' => 'Download Single',
                    'size' => '168 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC format',
                    'note' => 'A pop-oriented single with catchy hooks.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Like or Love', 'artist' => 'LiSA', 'duration' => '4:05'],
                    ['number' => '1.2', 'title' => 'Believe', 'artist' => 'LiSA', 'duration' => '3:58'],
                ],
                'editor_notes' => 'A more pop-oriented release showcasing LiSA\'s versatility.',
            ],

            // TK from Ling Tosite Sigure - 2 albums
            [
                'artist' => 'TK from Ling Tosite Sigure',
                'artist_slug' => 'tk-ling',
                'title' => 'Signal',
                'slug' => 'tk-signal',
                'type' => 'album',
                'genre' => 'Rock',
                'formats' => ['FLAC', '24-bit'],
                'release_date' => '2024-07-10',
                'originated' => '2024-07-10',
                'label' => 'Lastrum',
                'duration' => '41m 18s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/tk-signal.svg',
                    'alt' => 'Signal album cover',
                    'palette' => ['#212121', '#424242', '#757575'],
                    'accent' => '#ffffff',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/tk-ling/signal.zip',
                    'filename' => 'tk-signal.zip',
                    'label' => 'Download Album',
                    'size' => '567 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 96 kHz / 24-bit FLAC format',
                    'note' => 'Complex rhythms and angular guitar work signature TK style.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '96 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Signal', 'artist' => 'TK', 'duration' => '4:45'],
                    ['number' => '1.2', 'title' => 'Drain', 'artist' => 'TK', 'duration' => '3:58'],
                    ['number' => '1.3', 'title' => 'Encounter', 'artist' => 'TK', 'duration' => '4:22'],
                    ['number' => '1.4', 'title' => 'Kaleidoscope', 'artist' => 'TK', 'duration' => '4:35'],
                ],
                'editor_notes' => 'TK\'s solo work maintains the complex structures of his previous band.',
            ],
            [
                'artist' => 'TK from Ling Tosite Sigure',
                'artist_slug' => 'tk-ling',
                'title' => 'Pineapple',
                'slug' => 'tk-pineapple',
                'type' => 'ep',
                'genre' => 'Alternative',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2024-01-17',
                'originated' => '2024-01-17',
                'label' => 'Lastrum',
                'duration' => '20m 45s',
                'featured' => false,
                'recommended' => false,
                'cover' => [
                    'image' => 'images/audio/tk-pineapple.svg',
                    'alt' => 'Pineapple EP cover',
                    'palette' => ['#ffeb3b', '#ffc107', '#ff9800'],
                    'accent' => '#ff6f00',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/tk-ling/pineapple.zip',
                    'filename' => 'pineapple.zip',
                    'label' => 'Download EP',
                    'size' => '234 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC format',
                    'note' => 'A more experimental and eclectic EP.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Pineapple', 'artist' => 'TK', 'duration' => '4:12'],
                    ['number' => '1.2', 'title' => 'Maboroshi', 'artist' => 'TK', 'duration' => '3:45'],
                ],
                'editor_notes' => 'An experimental EP showing TK\'s more playful side.',
            ],

            // Hayato Nakamura - 2 albums
            [
                'artist' => 'Hayato Nakamura',
                'artist_slug' => 'hayato-nakamura',
                'title' => 'Piano Stories',
                'slug' => 'piano-stories',
                'type' => 'album',
                'genre' => 'Classical',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2024-08-21',
                'originated' => '2024-08-21',
                'label' => 'Victor Entertainment',
                'duration' => '55m 30s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/piano-stories.svg',
                    'alt' => 'Piano Stories album cover',
                    'palette' => ['#eceff1', '#cfd8dc', '#b0bec5'],
                    'accent' => '#37474f',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/hayato-nakamura/piano-stories.zip',
                    'filename' => 'piano-stories.zip',
                    'label' => 'Download Album',
                    'size' => '934 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 96 kHz / 24-bit FLAC format',
                    'note' => 'Beautiful piano compositions with cinematic quality.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '96 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Morning Light', 'artist' => 'Hayato Nakamura', 'duration' => '5:22'],
                    ['number' => '1.2', 'title' => 'Rainy Day', 'artist' => 'Hayato Nakamura', 'duration' => '4:45'],
                    ['number' => '1.3', 'title' => 'Starlight Waltz', 'artist' => 'Hayato Nakamura', 'duration' => '6:12'],
                    ['number' => '1.4', 'title' => 'Winter Solstice', 'artist' => 'Hayato Nakamura', 'duration' => '5:58'],
                ],
                'editor_notes' => 'Stunning piano compositions perfect for ambient listening.',
            ],
            [
                'artist' => 'Hayato Nakamura',
                'artist_slug' => 'hayato-nakamura',
                'title' => 'Dreaming',
                'slug' => 'dreaming',
                'type' => 'single',
                'genre' => 'Classical',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2025-01-01',
                'originated' => '2025-01-01',
                'label' => 'Victor Entertainment',
                'duration' => '12m 15s',
                'featured' => false,
                'recommended' => false,
                'cover' => [
                    'image' => 'images/audio/dreaming.svg',
                    'alt' => 'Dreaming single cover',
                    'palette' => ['#e8eaf6', '#c5cae9', '#9fa8da'],
                    'accent' => '#283593',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/hayato-nakamura/dreaming.zip',
                    'filename' => 'dreaming.zip',
                    'label' => 'Download Single',
                    'size' => '145 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC format',
                    'note' => 'A dreamy piano piece perfect for relaxation.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Dreaming', 'artist' => 'Hayato Nakamura', 'duration' => '6:08'],
                    ['number' => '1.2', 'title' => 'Lullaby', 'artist' => 'Hayato Nakamura', 'duration' => '6:07'],
                ],
                'editor_notes' => 'A peaceful piece ideal for winding down.',
            ],

            // Nujabes - 2 albums
            [
                'artist' => 'Nujabes',
                'artist_slug' => 'nujabes',
                'title' => 'Metaphorical Music',
                'slug' => 'metaphorical-music',
                'type' => 'album',
                'genre' => 'Hip Hop',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2023-09-21',
                'originated' => '2023-09-21',
                'label' => 'Hydeout Productions',
                'duration' => '47m 55s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/metaphorical-music.svg',
                    'alt' => 'Metaphorical Music album cover',
                    'palette' => ['#263238', '#4fc3f7', '#81d4fa'],
                    'accent' => '#e1f5fe',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/nujabes/metaphorical-music.zip',
                    'filename' => 'metaphorical-music.zip',
                    'label' => 'Download Album',
                    'size' => '512 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC and lossless formats',
                    'note' => 'A blend of hip-hop and jazz that defined the nu jazz genre.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Lift Off', 'artist' => 'Nujabes', 'duration' => '2:42'],
                    ['number' => '1.2', 'title' => 'Metaphorical Music', 'artist' => 'Nujabes', 'duration' => '3:12'],
                    ['number' => '1.3', 'title' => 'Beat Ladder', 'artist' => 'Nujabes', 'duration' => '2:58'],
                    ['number' => '1.4', 'title' => 'Orbit', 'artist' => 'Nujabes', 'duration' => '3:35'],
                    ['number' => '1.5', 'title' => 'Feather', 'artist' => 'Nujabes', 'duration' => '3:28'],
                ],
                'editor_notes' => 'A genre-defining album that put Nujabes on the map.',
            ],
            [
                'artist' => 'Nujabes',
                'artist_slug' => 'nujabes',
                'title' => 'Modal Soul',
                'slug' => 'modal-soul',
                'type' => 'album',
                'genre' => 'Jazz',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2024-03-12',
                'originated' => '2024-03-12',
                'label' => 'Hydeout Productions',
                'duration' => '44m 28s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/modal-soul.svg',
                    'alt' => 'Modal Soul album cover',
                    'palette' => ['#263238', '#81c784', '#a5d6a7'],
                    'accent' => '#e8f5e9',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/nujabes/modal-soul.zip',
                    'filename' => 'modal-soul.zip',
                    'label' => 'Download Album',
                    'size' => '678 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 96 kHz / 24-bit FLAC format',
                    'note' => 'Deep jazz influences with soulful production.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '96 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Channel 1', 'artist' => 'Nujabes', 'duration' => '2:58'],
                    ['number' => '1.2', 'title' => 'Modal Soul', 'artist' => 'Nujabes', 'duration' => '3:22'],
                    ['number' => '1.3', 'title' => 'Garden', 'artist' => 'Nujabes', 'duration' => '3:45'],
                    ['number' => '1.4', 'title' => 'Reflection', 'artist' => 'Nujabes', 'duration' => '4:12'],
                ],
                'editor_notes' => 'A more refined and mature work showcasing Nujabes\' growth.',
            ],

            // Ichiko Aoba - 2 albums
            [
                'artist' => 'Ichiko Aoba',
                'artist_slug' => 'ichiko-aoba',
                'title' => 'Windswept Adan',
                'slug' => 'windswept-adan',
                'type' => 'album',
                'genre' => 'Folk',
                'formats' => ['FLAC', '24-bit', 'Lossless'],
                'release_date' => '2024-04-17',
                'originated' => '2024-04-17',
                'label' => 'Riviera Records',
                'duration' => '39m 42s',
                'featured' => true,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/windswept-adan.svg',
                    'alt' => 'Windswept Adan album cover',
                    'palette' => ['#e8f5e9', '#c8e6c9', '#a5d6a7'],
                    'accent' => '#1b5e20',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/ichiko-aoba/windswept-adan.zip',
                    'filename' => 'windswept-adan.zip',
                    'label' => 'Download Album',
                    'size' => '456 MB',
                ],
                'specs' => [
                    'audio' => 'Available in 48 kHz / 24-bit FLAC format',
                    'note' => 'Delicate acoustic folk with nature-inspired soundscapes.',
                    'bit_depth' => '24-bit',
                    'sample_rate' => '48 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Adan', 'artist' => 'Ichiko Aoba', 'duration' => '4:15'],
                    ['number' => '1.2', 'title' => 'Hochi', 'artist' => 'Ichiko Aoba', 'duration' => '3:48'],
                    ['number' => '1.3', 'title' => 'Kokoro no na wa', 'artist' => 'Ichiko Aoba', 'duration' => '4:32'],
                    ['number' => '1.4', 'title' => 'Fukurou', 'artist' => 'Ichiko Aoba', 'duration' => '3:22'],
                ],
                'editor_notes' => 'A beautifully intimate folk album with delicate arrangements.',
            ],
            [
                'artist' => 'Ichiko Aoba',
                'artist_slug' => 'ichiko-aoba',
                'title' => 'Kamakura',
                'slug' => 'kamakura',
                'type' => 'ep',
                'genre' => 'Ambient',
                'formats' => ['FLAC', 'Lossless'],
                'release_date' => '2024-12-04',
                'originated' => '2024-12-04',
                'label' => 'Riviera Records',
                'duration' => '28m 35s',
                'featured' => false,
                'recommended' => true,
                'cover' => [
                    'image' => 'images/audio/kamakura.svg',
                    'alt' => 'Kamakura EP cover',
                    'palette' => ['#e3f2fd', '#90caf9', '#42a5f5'],
                    'accent' => '#1565c0',
                ],
                'download' => [
                    'enabled' => true,
                    'disk' => 'local',
                    'path' => 'audio/albums/ichiko-aoba/kamakura.zip',
                    'filename' => 'kamakura.zip',
                    'label' => 'Download EP',
                    'size' => '289 MB',
                ],
                'specs' => [
                    'audio' => 'Available in FLAC format',
                    'note' => 'Ambient compositions inspired by the city of Kamakura.',
                    'bit_depth' => '16-bit',
                    'sample_rate' => '44.1 kHz',
                ],
                'tracks' => [
                    ['number' => '1.1', 'title' => 'Morning in Kamakura', 'artist' => 'Ichiko Aoba', 'duration' => '5:12'],
                    ['number' => '1.2', 'title' => 'Sea Breeze', 'artist' => 'Ichiko Aoba', 'duration' => '4:45'],
                    ['number' => '1.3', 'title' => 'Temple Bell', 'artist' => 'Ichiko Aoba', 'duration' => '5:28'],
                ],
                'editor_notes' => 'A calming EP that captures the peaceful atmosphere of Kamakura.',
            ],
        ];
    }

    protected function seedAlbum(array $albumData): void
    {
        $artist = Artist::query()->updateOrCreate(
            ['slug' => $albumData['artist_slug']],
            ['name' => $albumData['artist']],
        );

        $album = Album::query()->updateOrCreate(
            [
                'artist_id' => $artist->id,
                'slug' => $albumData['slug'],
            ],
            [
                'title' => $albumData['title'],
                'type' => $albumData['type'] ?? 'album',
                'genre' => $albumData['genre'],
                'formats' => $albumData['formats'] ?? [],
                'release_date' => $albumData['release_date'] ?? null,
                'originated' => $albumData['originated'] ?? null,
                'label' => $albumData['label'] ?? null,
                'duration' => $albumData['duration'] ?? null,
                'featured' => $albumData['featured'] ?? false,
                'recommended' => $albumData['recommended'] ?? false,
                'cover_image' => data_get($albumData, 'cover.image'),
                'cover_alt' => data_get($albumData, 'cover.alt'),
                'cover_palette' => data_get($albumData, 'cover.palette', []),
                'cover_accent' => data_get($albumData, 'cover.accent'),
                'spec_audio' => data_get($albumData, 'specs.audio'),
                'spec_note' => data_get($albumData, 'specs.note'),
                'bit_depth' => data_get($albumData, 'specs.bit_depth'),
                'sample_rate' => data_get($albumData, 'specs.sample_rate'),
                'editor_notes' => $albumData['editor_notes'] ?? null,
            ],
        );

        $album->albumFormats()->delete();
        collect($albumData['formats'] ?? [])
            ->unique()
            ->values()
            ->each(fn (string $format) => $album->albumFormats()->create([
                'format' => $format,
            ]));

        $album->tracks()->delete();
        collect($albumData['tracks'] ?? [])
            ->values()
            ->each(function (array $trackData, int $index) use ($album) {
                [$discNumber, $trackNumber] = $this->parseDisplayNumber($trackData['number'] ?? null, $index + 1);

                $album->tracks()->create([
                    'disc_number' => $discNumber,
                    'track_number' => $trackNumber,
                    'display_number' => $trackData['number'] ?? '1.'.($index + 1),
                    'title' => $trackData['title'],
                    'artist_name' => $trackData['artist'] ?? null,
                    'duration' => $trackData['duration'] ?? null,
                    'sort_order' => $index + 1,
                ]);
            });

        $album->download()->updateOrCreate(
            ['album_id' => $album->id],
            Arr::only(array_merge([
                'enabled' => false,
                'disk' => 'local',
                'path' => null,
                'filename' => $albumData['slug'].'.zip',
                'label' => 'Download Album',
                'size' => null,
            ], $albumData['download'] ?? []), [
                'enabled',
                'disk',
                'path',
                'filename',
                'label',
                'size',
            ]),
        );
    }

    protected function parseDisplayNumber(?string $displayNumber, int $fallback): array
    {
        if (is_string($displayNumber) && preg_match('/^(\d+)\.(\d+)$/', $displayNumber, $matches)) {
            return [(int) $matches[1], (int) $matches[2]];
        }

        return [1, $fallback];
    }
}
