<?php

return [
    'brand' => [
        'title' => 'ABU-ABU READING',
        'subtitle' => 'Editorial library for journals, ebooks, and long-form notes.',
    ],

    'utility_nav' => [
        ['label' => 'Latest', 'href' => '#latest'],
        ['label' => 'Updated', 'href' => '#updated'],
        ['label' => 'Topics', 'href' => '#topics'],
        ['label' => 'Library', 'href' => '#catalog'],
    ],

    'local_nav' => [
        ['label' => 'Latest', 'href' => '#latest'],
        ['label' => 'Journals', 'href' => '#type-journal'],
        ['label' => 'E-books', 'href' => '#type-ebook'],
        ['label' => 'Topics', 'href' => '#topics'],
        ['label' => 'Updated', 'href' => '#updated'],
    ],

    'type_tabs' => [
        ['label' => 'All', 'value' => 'all'],
        ['label' => 'Journal', 'value' => 'journal'],
        ['label' => 'E-book', 'value' => 'ebook'],
        ['label' => 'Essay', 'value' => 'essay'],
        ['label' => 'Notes', 'value' => 'notes'],
    ],

    'topic_tabs' => [
        'All topics',
        'Design Systems',
        'Research Methods',
        'Editorial Practice',
        'Digital Archives',
        'Interface Writing',
    ],

    'sort_tabs' => [
        ['label' => 'Latest', 'value' => 'latest'],
        ['label' => 'Updated', 'value' => 'updated'],
        ['label' => 'Title', 'value' => 'title'],
    ],

    'hero' => [
        'eyebrow' => 'Reading room / editorial library',
        'title' => 'A brighter shelf for journals, ebooks, and long-form references.',
        'copy' => 'Reading inside Abu-Abu behaves like a quiet research desk: latest additions on top, updated items easy to scan, and filters that stay readable instead of noisy.',
    ],

    'promo' => [
        'label' => 'New & noteworthy',
        'link_label' => 'Open full library',
    ],

    'items' => [
        [
            'type' => 'journal',
            'slug' => 'quiet-systems-vol-12',
            'title' => 'Quiet Systems Vol. 12',
            'author' => 'Editorial Board',
            'year' => '2026',
            'topic' => 'Design Systems',
            'published_at' => '2026-03-28',
            'updated_at' => '2026-04-06',
            'summary' => 'A curated journal issue on steady interfaces, maintenance habits, and low-friction systems.',
            'abstract' => 'This issue examines how digital products stay legible over time: design debt, interface calm, and the editorial discipline behind product systems that age well.',
            'publisher' => 'Abu-Abu Review',
            'pages' => '148 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/quiet-systems-vol-12.svg',
                'alt' => 'Quiet Systems Vol. 12 cover',
                'palette' => ['#f6efe5', '#cab89a', '#3f3a33'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/journal/quiet-systems-vol-12.pdf',
                'filename' => 'quiet-systems-vol-12.pdf',
                'label' => 'Download PDF',
            ],
        ],
        [
            'type' => 'ebook',
            'slug' => 'field-guide-to-interface-writing',
            'title' => 'Field Guide to Interface Writing',
            'author' => 'Mara Ellison',
            'year' => '2025',
            'topic' => 'Interface Writing',
            'published_at' => '2026-03-10',
            'updated_at' => '2026-04-05',
            'summary' => 'A practical ebook on labels, flows, and the writing patterns that make interfaces feel calm.',
            'abstract' => 'This ebook breaks interface writing down into navigational language, system feedback, and editorial tone, with examples from archives, apps, and catalog products.',
            'publisher' => 'Signal Press',
            'pages' => '212 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/field-guide-to-interface-writing.svg',
                'alt' => 'Field Guide to Interface Writing cover',
                'palette' => ['#f0eadb', '#8b917f', '#2f342d'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/ebook/field-guide-to-interface-writing.pdf',
                'filename' => 'field-guide-to-interface-writing.pdf',
                'label' => 'Download E-book',
            ],
        ],
        [
            'type' => 'essay',
            'slug' => 'archive-thinking-for-small-teams',
            'title' => 'Archive Thinking for Small Teams',
            'author' => 'Nadia K. Rios',
            'year' => '2026',
            'topic' => 'Digital Archives',
            'published_at' => '2026-04-01',
            'updated_at' => '2026-04-04',
            'summary' => 'An essay about indexing, continuity, and why small teams need archival habits earlier than they think.',
            'abstract' => 'Rather than treating archives as a final-stage concern, this essay argues for lightweight structures early: naming, versioning, indexes, and editorial guardrails.',
            'publisher' => 'Abu-Abu Essays',
            'pages' => '36 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/archive-thinking-for-small-teams.svg',
                'alt' => 'Archive Thinking for Small Teams cover',
                'palette' => ['#f8f5ef', '#d7c8b0', '#4a4338'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/essay/archive-thinking-for-small-teams.pdf',
                'filename' => 'archive-thinking-for-small-teams.pdf',
                'label' => 'Download Essay',
            ],
        ],
        [
            'type' => 'journal',
            'slug' => 'methods-and-margins-08',
            'title' => 'Methods & Margins 08',
            'author' => 'Research Desk',
            'year' => '2025',
            'topic' => 'Research Methods',
            'published_at' => '2026-02-14',
            'updated_at' => '2026-04-02',
            'summary' => 'A methods issue for literature review structure, annotation systems, and tidy synthesis workflows.',
            'abstract' => 'Methods & Margins 08 collects short papers and notes on research framing, note-taking systems, source comparison, and maintaining clarity across iterative drafts.',
            'publisher' => 'Research Desk',
            'pages' => '128 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/methods-and-margins-08.svg',
                'alt' => 'Methods and Margins 08 cover',
                'palette' => ['#f3eee3', '#bba88d', '#2f2b26'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/journal/methods-and-margins-08.pdf',
                'filename' => 'methods-and-margins-08.pdf',
                'label' => 'Download PDF',
            ],
        ],
        [
            'type' => 'ebook',
            'slug' => 'calm-browsing-patterns',
            'title' => 'Calm Browsing Patterns',
            'author' => 'Leona Vale',
            'year' => '2024',
            'topic' => 'Design Systems',
            'published_at' => '2026-01-22',
            'updated_at' => '2026-03-30',
            'summary' => 'An ebook about search, filtering, and browse flows that feel structured without becoming cold.',
            'abstract' => 'Calm Browsing Patterns explores how to arrange discovery pages so they still look intentional at scale: rhythm, progressive filtering, metadata order, and visual pacing.',
            'publisher' => 'Shelf Form',
            'pages' => '186 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/calm-browsing-patterns.svg',
                'alt' => 'Calm Browsing Patterns cover',
                'palette' => ['#f7f1e8', '#c7b9a6', '#434038'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/ebook/calm-browsing-patterns.pdf',
                'filename' => 'calm-browsing-patterns.pdf',
                'label' => 'Download E-book',
            ],
        ],
        [
            'type' => 'notes',
            'slug' => 'editorial-room-notes-19',
            'title' => 'Editorial Room Notes 19',
            'author' => 'House Notes',
            'year' => '2026',
            'topic' => 'Editorial Practice',
            'published_at' => '2026-04-04',
            'updated_at' => '2026-04-04',
            'summary' => 'Short internal-style notes on curation, issue framing, and how to keep a shelf coherent over time.',
            'abstract' => 'This notes packet covers issue planning, cover cadence, annotation tone, and the small decisions that make a reading catalog feel edited rather than dumped.',
            'publisher' => 'Abu-Abu Notes',
            'pages' => '24 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/editorial-room-notes-19.svg',
                'alt' => 'Editorial Room Notes 19 cover',
                'palette' => ['#f2ebdf', '#c5b18e', '#39342b'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/notes/editorial-room-notes-19.pdf',
                'filename' => 'editorial-room-notes-19.pdf',
                'label' => 'Download Notes',
            ],
        ],
        [
            'type' => 'journal',
            'slug' => 'open-review-ledger-03',
            'title' => 'Open Review Ledger 03',
            'author' => 'Ledger Collective',
            'year' => '2026',
            'topic' => 'Research Methods',
            'published_at' => '2026-03-18',
            'updated_at' => '2026-03-29',
            'summary' => 'Peer-review style notes, argument maps, and synthesis patterns for collaborative editorial work.',
            'abstract' => 'Open Review Ledger 03 focuses on review practices that leave a trail: structured commentary, argument tracing, and lightweight decision records for teams.',
            'publisher' => 'Ledger Collective',
            'pages' => '94 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/open-review-ledger-03.svg',
                'alt' => 'Open Review Ledger 03 cover',
                'palette' => ['#f6f1e6', '#d4c5a7', '#413c32'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/journal/open-review-ledger-03.pdf',
                'filename' => 'open-review-ledger-03.pdf',
                'label' => 'Download PDF',
            ],
        ],
        [
            'type' => 'essay',
            'slug' => 'the-soft-index',
            'title' => 'The Soft Index',
            'author' => 'Irene Mott',
            'year' => '2025',
            'topic' => 'Editorial Practice',
            'published_at' => '2026-02-08',
            'updated_at' => '2026-03-24',
            'summary' => 'A long-form essay on why indexes can feel human, editorial, and surprisingly warm.',
            'abstract' => 'The Soft Index studies index structures as interface writing: not just where things are placed, but how sequences, labels, and summaries shape attention.',
            'publisher' => 'Paper Room',
            'pages' => '44 pages',
            'format' => 'PDF',
            'cover' => [
                'image' => 'images/reading/the-soft-index.svg',
                'alt' => 'The Soft Index cover',
                'palette' => ['#f4ede1', '#cdb48f', '#463b30'],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'reading/items/essay/the-soft-index.pdf',
                'filename' => 'the-soft-index.pdf',
                'label' => 'Download Essay',
            ],
        ],
    ],
];
