<?php

return [
    'brand' => [
        'title' => 'ABU-ABU TOOLS',
        'subtitle' => 'Workshop console for utilities, bundles, and recovery notes.',
    ],

    'utility_nav' => [
        ['label' => 'Featured', 'href' => '#featured'],
        ['label' => 'Games', 'href' => '#games'],
        ['label' => 'Packages', 'href' => '#packages'],
        ['label' => 'Recovery', 'href' => '#recovery'],
        ['label' => 'Updated', 'href' => '#updated'],
    ],

    'category_tabs' => [
        ['label' => 'All', 'value' => 'all'],
        ['label' => 'Utilities', 'value' => 'utilities'],
        ['label' => 'Installers', 'value' => 'installers'],
        ['label' => 'System', 'value' => 'system'],
        ['label' => 'Bundles', 'value' => 'bundles'],
        ['label' => 'Games', 'value' => 'games'],
    ],

    'os_tabs' => [
        ['label' => 'All', 'value' => 'all'],
        ['label' => 'Windows', 'value' => 'windows'],
        ['label' => 'Office', 'value' => 'office'],
        ['label' => 'Drivers', 'value' => 'drivers'],
        ['label' => 'Portable', 'value' => 'portable'],
        ['label' => 'CLI', 'value' => 'cli'],
        ['label' => 'VR', 'value' => 'vr'],
    ],

    'sort_tabs' => [
        ['label' => 'Featured', 'value' => 'featured'],
        ['label' => 'Updated', 'value' => 'updated'],
        ['label' => 'Title', 'value' => 'title'],
    ],

    'hero' => [
        'eyebrow' => 'Workshop console / legal software and games',
        'title' => 'Dense software shelves, a legal games archive, and a calmer recovery rail.',
        'copy' => 'Tools inside Abu-Abu should feel like an internal workbench: fast search, strong metadata, compact package rows, a release-style games archive, and a separate help lane for activation or repair guidance that stays legal.',
    ],

    'status_strip' => [
        ['label' => 'stable mirrors', 'value' => '04'],
        ['label' => 'help articles', 'value' => '04'],
        ['label' => 'bundle-ready', 'value' => '12'],
    ],

    'tools' => [
        [
            'slug' => 'activation-assistant',
            'title' => 'Activation Assistant',
            'vendor' => 'Abu-Abu Utilities',
            'version' => '2.4.1',
            'category' => 'utilities',
            'os' => ['windows', 'office'],
            'tags' => ['activation', 'license', 'repair'],
            'summary' => 'Checks license state, opens official recovery links, and collects activation diagnostics in one place.',
            'featured' => true,
            'accent' => '#C9FF4D',
            'icon' => 'AK',
            'updated_at' => '2026-04-05',
            'filesize' => '18.2 MB',
            'checksum' => 'SHA256 95E4...A8F2',
            'download_count' => '18.4k',
            'release_notes' => 'Adds a hardware-change checklist and a cleaner Office sign-in diagnostic summary.',
            'notes' => [
                'Open Microsoft activation pages directly from the tool.',
                'Exports a compact diagnostic report for support workflows.',
                'Does not generate keys or bypass activation checks.',
            ],
            'dependencies' => ['Windows Script Host', 'Microsoft Edge WebView2'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/activation-assistant.zip',
                'filename' => 'activation-assistant.zip',
                'label' => 'Download utility',
            ],
        ],
        [
            'slug' => 'driver-pack-helper',
            'title' => 'Driver Pack Helper',
            'vendor' => 'North Rail Labs',
            'version' => '1.9.0',
            'category' => 'system',
            'os' => ['windows', 'drivers'],
            'tags' => ['drivers', 'inventory', 'repair'],
            'summary' => 'Builds a driver inventory snapshot, highlights missing packages, and opens vendor download hubs.',
            'featured' => true,
            'accent' => '#F5B041',
            'icon' => 'DP',
            'updated_at' => '2026-04-06',
            'filesize' => '42.6 MB',
            'checksum' => 'SHA256 4A2F...C8D7',
            'download_count' => '12.1k',
            'release_notes' => 'Improves GPU and chipset detection for newer desktop boards.',
            'notes' => [
                'Useful before clean installs or recovery work.',
                'Pairs well with offline driver archives.',
            ],
            'dependencies' => ['.NET Desktop Runtime 8'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/driver-pack-helper.zip',
                'filename' => 'driver-pack-helper.zip',
                'label' => 'Download package',
            ],
        ],
        [
            'slug' => 'iso-verifier',
            'title' => 'ISO Verifier',
            'vendor' => 'Signal Forge',
            'version' => '3.2.3',
            'category' => 'utilities',
            'os' => ['windows', 'portable'],
            'tags' => ['checksum', 'iso', 'integrity'],
            'summary' => 'Verifies ISO hashes, labels release channels, and flags incomplete downloads before install.',
            'featured' => true,
            'accent' => '#7DE2D1',
            'icon' => 'IV',
            'updated_at' => '2026-04-03',
            'filesize' => '9.8 MB',
            'checksum' => 'SHA256 1BC2...77AD',
            'download_count' => '9.7k',
            'release_notes' => 'Now supports side-by-side checksum comparison for archive mirrors.',
            'notes' => [
                'Portable build included in the bundle.',
                'Keeps checksum history for recently verified images.',
            ],
            'dependencies' => ['None'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/iso-verifier.zip',
                'filename' => 'iso-verifier.zip',
                'label' => 'Download verifier',
            ],
        ],
        [
            'slug' => 'office-cleanup-tool',
            'title' => 'Office Cleanup Tool',
            'vendor' => 'Desk Relay',
            'version' => '5.0.2',
            'category' => 'utilities',
            'os' => ['office', 'windows'],
            'tags' => ['office', 'repair', 'cleanup'],
            'summary' => 'Removes broken Office traces, resets sign-in caches, and prepares the machine for a clean reinstall.',
            'featured' => false,
            'accent' => '#D4BFFF',
            'icon' => 'OC',
            'updated_at' => '2026-04-02',
            'filesize' => '27.5 MB',
            'checksum' => 'SHA256 71B2...31F0',
            'download_count' => '15.2k',
            'release_notes' => 'Adds a safer reset path for Microsoft 365 desktop profile issues.',
            'notes' => [
                'Designed for troubleshooting failed Office updates.',
                'Keeps a restore log before cleaning residual files.',
            ],
            'dependencies' => ['Administrator rights'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/office-cleanup-tool.zip',
                'filename' => 'office-cleanup-tool.zip',
                'label' => 'Download cleanup tool',
            ],
        ],
        [
            'slug' => 'portable-toolkit-lite',
            'title' => 'Portable Toolkit Lite',
            'vendor' => 'Abu-Abu Utilities',
            'version' => '1.5.8',
            'category' => 'bundles',
            'os' => ['portable', 'windows'],
            'tags' => ['portable', 'bundle', 'diagnostics'],
            'summary' => 'A compact USB-friendly pack with checksum tools, viewers, and small support utilities.',
            'featured' => true,
            'accent' => '#6EE7B7',
            'icon' => 'PT',
            'updated_at' => '2026-03-31',
            'filesize' => '148 MB',
            'checksum' => 'SHA256 AF56...11D0',
            'download_count' => '7.4k',
            'release_notes' => 'Bundle now includes the new log viewer and archive inspector.',
            'notes' => [
                'Prepared for technicians who move between machines.',
                'Keeps utilities separated by folder and role.',
            ],
            'dependencies' => ['USB drive or local folder'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/portable-toolkit-lite.zip',
                'filename' => 'portable-toolkit-lite.zip',
                'label' => 'Download bundle',
            ],
        ],
        [
            'slug' => 'bundle-installer-hub',
            'title' => 'Bundle Installer Hub',
            'vendor' => 'Relay Ops',
            'version' => '4.7.0',
            'category' => 'installers',
            'os' => ['windows', 'office'],
            'tags' => ['installer', 'bundle', 'deployment'],
            'summary' => 'Queues multiple legal installers, tracks progress, and exports an install log for handoff.',
            'featured' => true,
            'accent' => '#FFC857',
            'icon' => 'BI',
            'updated_at' => '2026-04-04',
            'filesize' => '63.7 MB',
            'checksum' => 'SHA256 34A8...CA10',
            'download_count' => '10.6k',
            'release_notes' => 'Adds grouped installer stages and a clearer retry queue.',
            'notes' => [
                'Inspired by batch installer workflows.',
                'Good for fresh workstation setups.',
            ],
            'dependencies' => ['Windows Installer service'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/bundle-installer-hub.zip',
                'filename' => 'bundle-installer-hub.zip',
                'label' => 'Download installer hub',
            ],
        ],
        [
            'slug' => 'system-health-checker',
            'title' => 'System Health Checker',
            'vendor' => 'Signal Forge',
            'version' => '6.1.4',
            'category' => 'system',
            'os' => ['windows', 'cli'],
            'tags' => ['system', 'logs', 'diagnostics'],
            'summary' => 'Runs quick health checks for storage, services, update state, and event log anomalies.',
            'featured' => false,
            'accent' => '#93C5FD',
            'icon' => 'SH',
            'updated_at' => '2026-04-07',
            'filesize' => '22.9 MB',
            'checksum' => 'SHA256 88A3...4FEA',
            'download_count' => '16.3k',
            'release_notes' => 'Improves scan performance and separates update failures from driver issues.',
            'notes' => [
                'Useful as a first-pass machine triage tool.',
                'Exports plain-text and JSON summaries.',
            ],
            'dependencies' => ['PowerShell 7 for advanced scripts'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/system-health-checker.zip',
                'filename' => 'system-health-checker.zip',
                'label' => 'Download checker',
            ],
        ],
        [
            'slug' => 'log-viewer-probe',
            'title' => 'Log Viewer Probe',
            'vendor' => 'North Rail Labs',
            'version' => '2.8.6',
            'category' => 'utilities',
            'os' => ['windows', 'cli'],
            'tags' => ['logs', 'viewer', 'support'],
            'summary' => 'Indexes setup logs and Windows event extracts into a smaller, easier support timeline.',
            'featured' => false,
            'accent' => '#FCA5A5',
            'icon' => 'LV',
            'updated_at' => '2026-03-29',
            'filesize' => '11.4 MB',
            'checksum' => 'SHA256 2198...AA5C',
            'download_count' => '6.1k',
            'release_notes' => 'Adds filtering for installer failures and activation-related events.',
            'notes' => [
                'Handy companion for recovery articles.',
                'Searches across grouped log folders.',
            ],
            'dependencies' => ['None'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/log-viewer-probe.zip',
                'filename' => 'log-viewer-probe.zip',
                'label' => 'Download viewer',
            ],
        ],
        [
            'slug' => 'office-license-reset',
            'title' => 'Office License Reset',
            'vendor' => 'Desk Relay',
            'version' => '1.3.9',
            'category' => 'installers',
            'os' => ['office', 'windows'],
            'tags' => ['office', 'activation', 'license'],
            'summary' => 'Clears cached activation sessions, resets licensing services, and links to official account repair pages.',
            'featured' => false,
            'accent' => '#A7F3D0',
            'icon' => 'OL',
            'updated_at' => '2026-04-01',
            'filesize' => '13.1 MB',
            'checksum' => 'SHA256 AC15...FF92',
            'download_count' => '8.9k',
            'release_notes' => 'Refines the Microsoft 365 sign-in reset sequence for multi-account machines.',
            'notes' => [
                'For support repair only, not key management.',
                'Best paired with the Office sign-in reset article.',
            ],
            'dependencies' => ['Administrator rights'],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/office-license-reset.zip',
                'filename' => 'office-license-reset.zip',
                'label' => 'Download reset tool',
            ],
        ],
        [
            'slug' => 'glass-harbor-vr',
            'title' => 'Glass Harbor VR',
            'vendor' => 'North Signal Games',
            'version' => 'Season 1 Build 1.0.4',
            'category' => 'games',
            'os' => ['windows', 'vr'],
            'tags' => ['game', 'vr', 'adventure'],
            'summary' => 'A legal VR adventure archive entry with release notes, mirror metadata, and setup guidance kept in one dense page.',
            'featured' => true,
            'accent' => '#7ee7ff',
            'icon' => 'GH',
            'updated_at' => '2026-04-07',
            'filesize' => '12.8 GB',
            'checksum' => 'SHA256 D4A9...90CE',
            'download_count' => '5.6k',
            'release_notes' => 'Adds headset profile fixes, cleaner controller hints, and a more stable first-run setup check.',
            'notes' => [
                'Prepared as a release-style game page, not a storefront cart page.',
                'Includes first-launch VR calibration notes and runtime prerequisites.',
                'Archive ships with launcher docs and controller mapping notes.',
            ],
            'dependencies' => ['SteamVR or OpenXR runtime', 'DirectX 12 GPU', '8 GB VRAM recommended'],
            'release_status' => 'Archive ready',
            'license_state' => 'Requires official license',
            'build_type' => 'Installer archive',
            'archive_notes' => [
                'Mirror package contains the main installer and a separate bonus-content folder.',
                'Checksums verified against the current production build export.',
            ],
            'screenshots' => [
                ['title' => 'Dock arrival', 'tone' => 'cyan dusk'],
                ['title' => 'Workshop corridor', 'tone' => 'teal fog'],
                ['title' => 'Harbor overlook', 'tone' => 'violet glass'],
            ],
            'requirements' => [
                'minimum' => [
                    'OS: Windows 10 64-bit',
                    'CPU: Ryzen 5 3600 / Core i5-10400',
                    'Memory: 16 GB RAM',
                    'GPU: RTX 2060 / RX 6700 XT',
                    'VR: OpenXR compatible headset',
                    'Storage: 24 GB available space',
                ],
                'recommended' => [
                    'OS: Windows 11 64-bit',
                    'CPU: Ryzen 7 5800X / Core i7-12700',
                    'Memory: 32 GB RAM',
                    'GPU: RTX 3080 / RX 7900 XT',
                    'VR: Valve Index / Quest Link / WMR via OpenXR',
                    'Storage: SSD with 24 GB free',
                ],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/glass-harbor-vr.zip',
                'filename' => 'glass-harbor-vr.zip',
                'label' => 'Download game archive',
            ],
        ],
        [
            'slug' => 'skyframe-zero-demo',
            'title' => 'Skyframe Zero Demo',
            'vendor' => 'Abu-Abu Arcade',
            'version' => 'Demo 0.9.2',
            'category' => 'games',
            'os' => ['windows'],
            'tags' => ['game', 'demo', 'action'],
            'summary' => 'A demo archive for a fast arena action game, packaged with release metadata, system requirements, and mirror notes.',
            'featured' => true,
            'accent' => '#ffd166',
            'icon' => 'SZ',
            'updated_at' => '2026-04-04',
            'filesize' => '6.4 GB',
            'checksum' => 'SHA256 71D1...13AC',
            'download_count' => '4.1k',
            'release_notes' => 'Refreshes gamepad prompts and reduces stutter during the second stage transition.',
            'notes' => [
                'Demo build intended for preview and benchmark-style testing.',
                'Includes optional high-resolution texture pack as a second archive part.',
            ],
            'dependencies' => ['Visual C++ Redistributable 2022', 'Gamepad optional'],
            'release_status' => 'Demo available',
            'license_state' => 'Free demo',
            'build_type' => 'Portable archive',
            'archive_notes' => [
                'Main archive extracts directly to a runnable folder.',
                'High-resolution texture pack is optional and listed separately in the package notes.',
            ],
            'screenshots' => [
                ['title' => 'Combat arena', 'tone' => 'amber flood'],
                ['title' => 'Boss approach', 'tone' => 'orange signal'],
            ],
            'requirements' => [
                'minimum' => [
                    'OS: Windows 10 64-bit',
                    'CPU: Ryzen 5 2600 / Core i5-8400',
                    'Memory: 12 GB RAM',
                    'GPU: GTX 1660 / RX 5600 XT',
                    'Storage: 12 GB available space',
                ],
                'recommended' => [
                    'OS: Windows 11 64-bit',
                    'CPU: Ryzen 7 5700X / Core i7-11700',
                    'Memory: 16 GB RAM',
                    'GPU: RTX 3070 / RX 6800',
                    'Storage: SSD with 12 GB free',
                ],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/skyframe-zero-demo.zip',
                'filename' => 'skyframe-zero-demo.zip',
                'label' => 'Download demo archive',
            ],
        ],
        [
            'slug' => 'paper-trails-community-edition',
            'title' => 'Paper Trails Community Edition',
            'vendor' => 'Paper Trails Team',
            'version' => 'Community Build 2.1.0',
            'category' => 'games',
            'os' => ['windows', 'portable'],
            'tags' => ['game', 'drm-free', 'story'],
            'summary' => 'A DRM-free story game archive entry with calm release notes, mirror data, and install guidance.',
            'featured' => false,
            'accent' => '#cdb4db',
            'icon' => 'PT',
            'updated_at' => '2026-03-28',
            'filesize' => '3.9 GB',
            'checksum' => 'SHA256 F90D...4B21',
            'download_count' => '2.7k',
            'release_notes' => 'Community build refresh with language pack cleanup and subtitle timing fixes.',
            'notes' => [
                'DRM-free package with optional soundtrack folder.',
                'Good example of how the games archive can stay tidy without storefront clutter.',
            ],
            'dependencies' => ['None'],
            'release_status' => 'Community archive',
            'license_state' => 'DRM-free',
            'build_type' => 'Portable archive',
            'archive_notes' => [
                'Single archive, no external launcher required.',
                'Soundtrack folder ships as an optional extra in the same package.',
            ],
            'screenshots' => [
                ['title' => 'Town square', 'tone' => 'paper dusk'],
                ['title' => 'Train compartment', 'tone' => 'lavender smoke'],
            ],
            'requirements' => [
                'minimum' => [
                    'OS: Windows 10 64-bit',
                    'CPU: Ryzen 3 3300X / Core i3-10100',
                    'Memory: 8 GB RAM',
                    'GPU: GTX 1050 Ti / RX 570',
                    'Storage: 8 GB available space',
                ],
                'recommended' => [
                    'OS: Windows 11 64-bit',
                    'CPU: Ryzen 5 5600 / Core i5-12400',
                    'Memory: 16 GB RAM',
                    'GPU: RTX 3060 / RX 6700 XT',
                    'Storage: SSD with 8 GB free',
                ],
            ],
            'download' => [
                'enabled' => true,
                'disk' => 'local',
                'path' => 'tools/packages/paper-trails-community-edition.zip',
                'filename' => 'paper-trails-community-edition.zip',
                'label' => 'Download community build',
            ],
        ],
    ],

    'help_articles' => [
        [
            'slug' => 'windows-activation-troubleshooting',
            'title' => 'Windows activation troubleshooting',
            'product' => 'Windows 11 / Windows 10',
            'summary' => 'A quick path for checking license state, error codes, and official recovery steps after failed activation.',
            'symptoms' => [
                'Activation banner keeps returning after restart.',
                'Error appears after reinstall or motherboard changes.',
                'Digital license cannot be matched to the current device.',
            ],
            'steps' => [
                'Confirm the machine edition matches the purchased license.',
                'Open activation settings and run the built-in troubleshooter.',
                'Use Activation Assistant to collect error codes and license state.',
                'Sign in with the Microsoft account tied to the digital license.',
            ],
            'related_tools' => ['activation-assistant', 'system-health-checker'],
        ],
        [
            'slug' => 'office-sign-in-reset',
            'title' => 'Office sign-in reset',
            'product' => 'Microsoft 365 / Office 2021',
            'summary' => 'Fixes loops between expired sign-in sessions, broken Office cache files, and partial activation states.',
            'symptoms' => [
                'Office keeps asking to sign in again.',
                'Apps open as unlicensed even after successful account login.',
                'Activation works in one app but fails in another.',
            ],
            'steps' => [
                'Sign out from all Office apps and close background helpers.',
                'Run Office Cleanup Tool or Office License Reset to clear stale data.',
                'Open an Office app and sign in with the correct licensed account.',
                'Verify subscription state in the Microsoft account portal.',
            ],
            'related_tools' => ['office-cleanup-tool', 'office-license-reset'],
        ],
        [
            'slug' => 'hardware-change-reactivation',
            'title' => 'Reactivation after hardware changes',
            'product' => 'Windows devices after major hardware changes',
            'summary' => 'Use this flow when Windows stops recognizing a previously activated device after board or storage replacement.',
            'symptoms' => [
                'Activation was fine before replacing the motherboard.',
                'The device now shows as unactivated after component swaps.',
            ],
            'steps' => [
                'Check whether the original license is transferable.',
                'Sign in with the same Microsoft account used before the hardware change.',
                'Run the activation troubleshooter and select the matching device.',
                'Review the support log before contacting Microsoft support.',
            ],
            'related_tools' => ['activation-assistant', 'driver-pack-helper'],
        ],
        [
            'slug' => 'installer-repair-checklist',
            'title' => 'Installer repair checklist',
            'product' => 'Desktop installers and utility bundles',
            'summary' => 'A compact checklist for broken installers, missing runtimes, and interrupted package deployments.',
            'symptoms' => [
                'Installer exits without a useful error message.',
                'Runtime prerequisites are missing or corrupt.',
                'Package logs are too noisy to triage quickly.',
            ],
            'steps' => [
                'Verify the archive hash before extracting the package.',
                'Check required runtimes and Windows Installer service state.',
                'Review the failure log with Log Viewer Probe.',
                'Retry using Bundle Installer Hub after cleanup.',
            ],
            'related_tools' => ['iso-verifier', 'bundle-installer-hub', 'log-viewer-probe'],
        ],
    ],
];
